version: '3.9'

x-common-env: &common-env
  GOPATH: /go
  GOCACHE: /src/.cache/gocache
  MONGO_URL: mongodb://mongo:27017/
  MONGO_DATABASE: nthu_distributes_system
  POSTGRES_URL: postgres://postgres@postgres:5432/postgres?sslmode=disable
  REDIS_ADDR: redis:6379
  # KAFKA_ADDR:
  MINIO_ENDPOINT: play.min.io
  MINIO_BUCKET: videos
  MINIO_USERNAME: Q3AM3UQ867SPQQA43P2F
  MINIO_PASSWORD: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG

x-common-build: &common-build
  image: justin0u0/golang-protoc:protoc-3.19.3-golang-1.17
  working_dir: /src
  environment:
    <<: *common-env
  volumes:
  - .:/src
  - ~/go/pkg/mod/cache:/go/pkg/mod/cache

services:
  mongo:
    image: mongo:5

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:6.2-alpine

  generate:
    <<: *common-build
    command:
    - make
    - generate

  lint:
    image: golangci/golangci-lint:v1.44.0
    working_dir: /src
    environment:
      GOLANGCI_LINT_CACHE: /src/.cache/golangci-lint-cache
    volumes:
    - .:/src
    command:
    - make
    - lint

  test:
    <<: *common-build
    command:
    - make
    - test
    depends_on:
    - mongo
    - redis
    - postgres

  build:
    <<: *common-build
    command:
    - make
    - build

  image:
    image: nthu-distributed-system:latest
    build:
      context: .
    environment:
      <<: *common-env

  video-api:
    image: nthu-distributed-system:latest
    environment:
      <<: *common-env
    command:
    - /cmd
    - video
    - api
    depends_on:
    - mongo
    - redis
    - postgres

  video-gateway:
    image: nthu-distributed-system:latest
    environment:
      <<: *common-env
      GRPC_ADDR: video-api:8081
    command:
    - /cmd
    - video
    - gateway
    ports:
    - 10080:8080
