version: '3.9'

x-common-env: &common-env
  MONGO_URL: mongodb://mongo:27017/
  # POSTGRES_URL: postgres://postgres@postgres:5432/postgres?sslmode=disable
  # REDIS_ADDR: redis:6379
  # KAFKA_ADDR:

x-common-build: &common-build
  image: justin0u0/golang-protoc:protoc-3.19.3-golang-1.17
  working_dir: /src
  environment:
    <<: *common-env
    GOPATH: /go
    GOCACHE: /src/.cache/gocache
  volumes:
  - .:/src
  - ~/go/pkg/mod/cache:/go/pkg/mod/cache

services:
  mongo:
    image: mongo:5

  generate:
    <<: *common-build
    command:
    - make
    - generate

  test:
    <<: *common-build
    command:
    - make
    - test
    depends_on:
    - mongo
