
name: main workflow

on: push

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.44.0
  
  build:
    runs-on: ubuntu-20.04
    env:
      DOCKER_COMPOSE: docker-compose
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: cache
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: test
      run: make dc.test

    - name: image
      run: make dc.image

    - name: login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: push
      run: |
        docker tag nthu-distributed-system:latest nthu-distributed-system:$GITHUB_SHA
        docker push nthu-distributed-system:latest
        docker push nthu-distributed-system:$GITHUB_SHA
