
name: main workflow

on: push

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.44.0
  
  build:
    runs-on: ubuntu-20.04
    env:
      DOCKER_COMPOSE: docker-compose
      REGISTRY: ghcr.io
      OWNER: nthu-lsalab
      GOFLAGS: -modcacherw
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
        check-latest: true

    - name: cache
      uses: actions/cache@v2.1.7
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: go-cache-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          go-cache

    - name: test
      run: make dc.test

    - name: image
      run: make dc.image

    - name: login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: push
      run: |
        docker tag nthu-distributed-system:latest ${{ env.REGISTRY }}/${{ env.OWNER }}/nthu-distributed-system:latest
        docker tag nthu-distributed-system:latest ${{ env.REGISTRY }}/${{ env.OWNER }}/nthu-distributed-system:${{ github.sha }}
        docker push ${{ env.REGISTRY }}/${{ env.OWNER }}/nthu-distributed-system:latest
        docker push ${{ env.REGISTRY }}/${{ env.OWNER }}/nthu-distributed-system:${{ github.sha }}
